spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gj?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
server:
  context-path: /wechat
  port: 9898
gj:
  prop:
#    appid: wx4d033972d3910170
#    secret: b9093efbfe18128340f0be66d9a97ba7
    appid: wx3bb698ca6c90ed80
    secret: b13b5c52b0408d756d6ea81d7b5f6379
    affixDir: D:/dev/zz_affix/gj
#    webDomain: http://172.20.1.57:8080
    webDomain: http://192.168.0.100:8080
